export type AuditPdfData = {
  auditNumber: string;
  zone: string;
  department: string;
  auditorName: string;
  date: string;
  totalScore: number;
  categoryScores?: Record<string, number | { score?: number }>;
  checklist: Array<{
    category: string;
    question: string;
    response: string;
    observation?: string;
    severity?: string;
  }>;
};

function categoryScore(value: number | { score?: number }) {
  return typeof value === "number" ? value : value?.score ?? 0;
}

export async function downloadAuditPdf(audit: AuditPdfData) {
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable")
  ]);

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(239, 43, 45);
  doc.rect(0, 0, pageWidth, 5, "F");
  doc.setTextColor(30, 41, 59);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("6S AuditPro", 14, 17);
  doc.setFontSize(13);
  doc.text(`Audit Report - ${audit.auditNumber}`, 14, 26);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text("OnePWS Private Limited", 14, 32);

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 38, pageWidth - 28, 29, 2, 2, "F");
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);
  doc.text(`Zone: ${audit.zone}`, 18, 46);
  doc.text(`Department: ${audit.department}`, 18, 53);
  doc.text(`Auditor: ${audit.auditorName}`, 18, 60);
  doc.text(`Audit Date: ${new Date(audit.date).toLocaleDateString()}`, 108, 46);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(audit.totalScore >= 90 ? 21 : 185, audit.totalScore >= 90 ? 128 : 28, audit.totalScore >= 90 ? 61 : 28);
  doc.text(`Overall Score: ${audit.totalScore}%`, 108, 56);

  const categoryRows = Object.entries(audit.categoryScores || {}).map(([category, score]) => [
    category,
    `${categoryScore(score)}%`
  ]);

  autoTable(doc, {
    startY: 73,
    head: [["Pillar", "Score"]],
    body: categoryRows.length ? categoryRows : [["No category scores", "-"]],
    theme: "grid",
    headStyles: { fillColor: [30, 41, 59], textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8, cellPadding: 2.2 },
    columnStyles: { 1: { halign: "right", cellWidth: 28 } }
  });

  const afterScores = (doc as typeof doc & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 83;
  autoTable(doc, {
    startY: afterScores + 7,
    head: [["#", "Pillar", "Checklist Item", "Response", "Severity", "Observation"]],
    body: audit.checklist.map((item, index) => [
      String(index + 1),
      item.category,
      item.question,
      item.response,
      item.severity || "-",
      item.observation || "-"
    ]),
    theme: "grid",
    headStyles: { fillColor: [239, 43, 45], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 7, cellPadding: 1.8, overflow: "linebreak", valign: "top" },
    columnStyles: {
      0: { cellWidth: 8, halign: "center" },
      1: { cellWidth: 25 },
      2: { cellWidth: 62 },
      3: { cellWidth: 25 },
      4: { cellWidth: 20 },
      5: { cellWidth: 42 }
    },
    didDrawPage: () => {
      const pageNumber = doc.getNumberOfPages();
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text(`Generated by 6S AuditPro | Page ${pageNumber}`, 14, 291);
    }
  });

  const safeName = audit.auditNumber.replace(/[^a-z0-9-_]/gi, "_");
  doc.save(`${safeName}_Audit_Report.pdf`);
}
